# Generated by Django 4.1.3 on 2022-11-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appseba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_de_naciemiento',
            new_name='nacim',
        ),
    ]
